### ISSUE TITLE
Regarding codebase release!!

### ISSUE THREAD

**Issue by coreqode** [omegaiota/DiffCloth#1]
Hi! This is super-awesome work. When can we expect the release of codebase?

**Comment by omegaiota** [comment]
Hi, thanks for being interested in our work! I am cleaning up the code and should release the code by early August!

**Comment by fire** [comment]
Amazing work!

**Comment by ForrestPi** [comment]
hope for codebase release

**Comment by omegaiota** [comment]
Hi, sorry for the long wait. 

I've just released the code. Feel free to contact me through email or creating a new issue if you have any questions regarding setting up the code base, running examples or setting up new example.
