### ISSUE TITLE
Run clang format over DiffCloth

### ISSUE THREAD

**Issue by fire** [omegaiota/DiffCloth#12]
I noticed that the code was a bit uneven and makes diffs difficult.

Would you be interested in a clang-format pull request?

**Comment by omegaiota** [comment]
Sure that would be helpful!

**Comment by fire** [comment]
So the first thing would be to guess your coding style

I have a procedure from https://github.com/AcademySoftwareFoundation/MaterialX/issues/652

**Comment by fire** [comment]
Closing due lack of interest.
