### ISSUE TITLE
Simulation with dirvenable human model

### ISSUE THREAD

**Issue by fishfishson** [omegaiota/DiffCloth#13]
Hi author,
Thx for your great work on cloth simulation. Since there are many ways to reconstruct dynamic human geometry along with cloth parsing masks. I wonder can this work simulate cloth given a sequence of dynamic human 3D models?

**Comment by omegaiota** [comment]
Hi,
   Not yet as the collision detection algorithm implemented in the codebase only supports simple geometry primitives (sphere, plane, capsules etc.). Once a collision detection algorithm for arbitrary meshes are implemented I think supporting  human models will be trivial ( See https://github.com/omegaiota/DiffCloth/issues/10 ).
