### ISSUE TITLE
Code released: physics engine or optimizers!

### ISSUE THREAD

**Issue by alelordelo** [omegaiota/DiffCloth#2]
Hello team, thanks for sharing this amazing paper!

Will you guys release the optimizer or a complete physics engine?

thanks!

**Comment by omegaiota** [comment]
Hi, sorry for the long wait. 

I've just released the code. Feel free to contact me through email or creating a new issue if you have any questions regarding setting up the code base, running examples or setting up new example.

**Comment by alelordelo** [comment]
Hi @omegaiota 
I am getting this build error bellow on MacBook Air M1  MacOS Ventura.

Any idea how to fix it would be hugely appreciated! : )

build % cmake ..
-- set env var
-- Using Cocoa for window creation
CMake Error at /Applications/CMake.app/Contents/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES)
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /Applications/CMake.app/Contents/share/cmake-3.24/Modules/FindOpenMP.cmake:545 (find_package_handle_standard_args)
  CMakeLists.txt:70 (find_package)


-- Configuring incomplete, errors occurred!

**Comment by alelordelo** [comment]
Update...


I fount this SO, but looks like you guys already included the code on the file...

<img width="1440" alt="Screenshot 2022-11-01 at 14 27 23" src="https://user-images.githubusercontent.com/17708751/199244360-49417e8e-3eed-4355-9329-0fc0add73a5a.png">

**Comment by omegaiota** [comment]
Can you double check if you've installed OpenMP?

**Comment by alelordelo** [comment]
Sorry for the late reply, was out last week...
I re installed all Packages and now it works! Thanks a lot for looking into this @omegaiota!

**Comment by omegaiota** [comment]
👍🏻
