### ISSUE TITLE
Licensed under MIT license?

### ISSUE THREAD

**Issue by fire** [omegaiota/DiffCloth#4]
Hi!

![image](https://user-images.githubusercontent.com/32321/196082685-9bd3c970-25fd-4e36-9039-8f3d57298b66.png)

I was wondering if this was licensed under MIT license to match Godot Engine's license https://github.com/godotengine/godot/blob/master/LICENSE.txt

Thank you for releasing this amazing work.

**Comment by omegaiota** [comment]
Yes; I just added MIT license to the repo.
