### ISSUE TITLE
Pip subprocess error

### ISSUE THREAD

**Issue by liangqx-hku** [omegaiota/DiffCloth#8]
Hi Yifei,

Thanks for sharing your wonderful work,
When I try to build python binding, I hit this problem:
Pip subprocess error:
ERROR: Could not find a version that satisfies the requirement diffcloth-py==0.0.1
ERROR: No matching distribution found for diffcloth-py==0.0.1

failed

CondaEnvException: Pip failed
When I dive into the conda env diffcloth, and try the cmd: pip install diffcloth-py==0.0. I hit the same error again.
So, could you give me some advice to deal with it?(my workstation is Ubuntu 20.04)
Many thanks,

-Leung

**Comment by sihengz02** [comment]
one possible way to solve is converting the order :
 -  delete `diffcloth-py=0.0.1` in `environment.yml`
 -  `conda env create python=3.8 --file environment.yml`
 - `python setup.py install`

**Comment by liangqx-hku** [comment]
> one possible way to solve is converting the order :
> 
>     * delete `diffcloth-py=0.0.1` in `environment.yml`
> 
>     * `conda env create python=3.8 --file environment.yml`
> 
>     * `python setup.py install`

Thanks for your prompt reply, it works well now!
