### ISSUE TITLE
Restore windows support.

### ISSUE THREAD

**Issue by fire** [omegaiota/DiffCloth#9]
Hi!

I spent some time getting Windows support.

https://github.com/omegaiota/DiffCloth/compare/main...fire:differentiable_cloth:drop_python

Maybe you have some use of this.

It's a bit messy.

1. ran clang format
2. skipped python integration
3. use c++17 std::filesystem
4. some changes to the cmakelist for glfw and glad
5. misc new lines add to printed string
6. the global enum POINT is already defined. Rename to CAMERA_POINT.
7. Does not automatically do the required steps to copy glfw3.dll, libnangui.dll and libomp.dll to the build directory.
8. Had to disable preview after every iteration because of a crash in the renderer
9. Easiest was to upgrade nanogui for the glad deps

**Comment by omegaiota** [comment]
Hi Fire,
    I'll take a look at this and find some time to work on build support for Windows. Your notes will be very helpful.

**Comment by fire** [comment]
`cmake -DGLFW_USE_WAYLAND=ON ..`
